#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

# Run from the LoughdIn checkout in Git Bash:  bash scripts/release-signing-wizard.sh
# Passwords are typed here, passed to keytool/gh through the environment and
# pipes, and never written to disk or shell history. Nothing goes to .env.

TOTAL_STAGES=6
# The password and backup prompts loop until answered, so refuse to start
# without a terminal to answer them.
[[ -t 0 ]] || { warn "Run this in an interactive terminal: bash scripts/release-signing-wizard.sh"; exit 1; }
REPO="padraigbros/LoughdIn"
KEY_ALIAS="loughdin"
KEY_DIR="${LOUGHDIN_KEY_DIR:-$HOME/.loughdin-release}"
KEYSTORE="$KEY_DIR/loughdin-release.jks"

banner "Lough'd In: signed Android release"

# ── Stage 1 ───────────────────────────────────────────────────────────────
stage "Check tools and repository"
KEYTOOL=""
for candidate in "${JAVA_HOME:+$JAVA_HOME/bin/keytool}" "/c/Program Files/Android/Android Studio/jbr/bin/keytool" "$(command -v keytool || true)"; do
  if [[ -n "$candidate" && ( -x "$candidate" || -x "$candidate.exe" ) ]]; then KEYTOOL="$candidate"; break; fi
done
[[ -n "$KEYTOOL" ]] || { warn "keytool not found. Install Android Studio or set JAVA_HOME to a JDK, then re-run."; exit 1; }
say "keytool: $KEYTOOL"
command -v gh >/dev/null 2>&1 || { warn "GitHub CLI (gh) is not installed."; exit 1; }
if ! gh auth status >/dev/null 2>&1; then
  warn "gh is not logged in. If 'gh auth status' says logged out right after a login, check %APPDATA%\\GitHub CLI\\hosts.yml is not '{}'."
  exit 1
fi
remote_repo=$(gh repo view --json nameWithOwner --jq .nameWithOwner 2>/dev/null || true)
[[ "$remote_repo" == "$REPO" ]] || { warn "Run this from the $REPO checkout (gh sees '${remote_repo:-no repo}')."; exit 1; }
say "GitHub CLI is logged in and pointed at $REPO."
pause

# ── Stage 2 ───────────────────────────────────────────────────────────────
stage "Create the upload key"
say "The upload key is the app's identity. Every future APK must be signed with it,"
say "or Android refuses to update the installed app. It lives outside the repo:"
note "$KEYSTORE"
mkdir -p "$KEY_DIR"
while :; do
  ask_secret LOUGHDIN_STOREPASS "Choose the keystore password (at least 12 characters):"
  if [[ -f "$KEYSTORE" ]]; then
    export LOUGHDIN_STOREPASS
    if "$KEYTOOL" -list -keystore "$KEYSTORE" -storepass:env LOUGHDIN_STOREPASS -alias "$KEY_ALIAS" >/dev/null 2>&1; then
      say "A keystore already exists there and the password opens it, so it will be reused."
      break
    fi
    warn "A keystore already exists at that path and this password does not open it. Try again."
    continue
  fi
  if (( ${#LOUGHDIN_STOREPASS} < 12 )); then warn "Use at least 12 characters."; continue; fi
  ask_secret LOUGHDIN_STOREPASS_AGAIN "Type it again:"
  [[ "$LOUGHDIN_STOREPASS" == "$LOUGHDIN_STOREPASS_AGAIN" ]] || { warn "The passwords did not match."; continue; }
  unset LOUGHDIN_STOREPASS_AGAIN
  export LOUGHDIN_STOREPASS
  say "keytool will now ask for a name and organisation for the certificate."
  note "Anything accurate is fine, e.g. your name, 'Lough'd In', and country code IE."
  # PKCS12 keystores use the store password for the key as well.
  "$KEYTOOL" -genkeypair -v -keystore "$KEYSTORE" -storetype PKCS12 -alias "$KEY_ALIAS" \
    -keyalg RSA -keysize 4096 -validity 10000 -storepass:env LOUGHDIN_STOREPASS
  break
done
say "Keystore ready."
pause

# ── Stage 3 ───────────────────────────────────────────────────────────────
stage "Record the fingerprint and back up the key"
fingerprint=$("$KEYTOOL" -list -v -keystore "$KEYSTORE" -storepass:env LOUGHDIN_STOREPASS -alias "$KEY_ALIAS" | grep -m1 'SHA256:' | sed 's/.*SHA256: *//')
say "Certificate SHA-256 fingerprint:"
printf '\n    %s%s%s\n\n' "$BOLD" "$fingerprint" "$RESET"
step "In your password manager, create an entry 'Lough'd In Android upload key'."
step "Attach the file $KEYSTORE to it."
step "Save the password you just chose, the alias '$KEY_ALIAS' and the fingerprint above."
step "Keep a second copy of the .jks file offline (e.g. a USB drive)."
warn "If this key is lost, installed copies can never be updated. There is no recovery."
until confirm "Is the keystore file and its password saved in your password manager and backed up?"; do
  say "Take your time. The wizard will wait."
done

# ── Stage 4 ───────────────────────────────────────────────────────────────
stage "Store the key as GitHub secrets"
say "The release workflow reads four repository secrets. The values go straight"
say "from this terminal to GitHub over gh and are not printed."
set_secret LOUGHDIN_KEYSTORE_BASE64 "$(base64 -w0 "$KEYSTORE")"
set_secret LOUGHDIN_KEYSTORE_PASSWORD "$LOUGHDIN_STOREPASS"
set_secret LOUGHDIN_KEY_ALIAS "$KEY_ALIAS"
set_secret LOUGHDIN_KEY_PASSWORD "$LOUGHDIN_STOREPASS"
unset LOUGHDIN_STOREPASS
if (( ${#SKIPPED[@]} )); then warn "Some secrets were not set. Fix gh and re-run; the existing keystore will be reused."; exit 1; fi
say "Secrets now on GitHub:"
gh secret list --repo "$REPO" | grep '^LOUGHDIN_' | sed 's/^/    /'
pause

# ── Stage 5 ───────────────────────────────────────────────────────────────
stage "Tag the release and watch the build"
while :; do
  git fetch -q origin
  has_workflow=$(git cat-file -e origin/master:.github/workflows/android-release.yml 2>/dev/null && echo yes || echo no)
  version=$(git show origin/master:package.json | node -p "JSON.parse(require('fs').readFileSync(0,'utf8')).version")
  [[ "$has_workflow" == yes && "$version" != "0.3.0" ]] && break
  [[ "$has_workflow" == yes ]] || step "Merge the 'Build release-signed Android APKs' pull request."
  [[ "$version" != "0.3.0" ]] || step "Merge the version bump pull request (master is still $version)."
  open_url "https://github.com/$REPO/pulls"
  pause "Press Enter once merged, to check again"
done
TAG="v$version"
if git ls-remote --exit-code --tags origin "refs/tags/$TAG" >/dev/null 2>&1; then
  say "Tag $TAG already exists on GitHub, so its release run is reused."
else
  say "master is at $(git rev-parse --short origin/master) with version $version."
  if ! confirm "Push tag $TAG? This builds and publishes a public GitHub Release."; then
    say "Stopped before tagging. Re-run the wizard when you are ready."; exit 0
  fi
  git tag -a "$TAG" origin/master -m "Lough'd In $version"
  git push origin "$TAG"
fi
say "Waiting for the Android release workflow to start…"
run_id=""
for _ in $(seq 1 30); do
  run_id=$(gh run list --repo "$REPO" --workflow android-release.yml --branch "$TAG" --limit 1 --json databaseId --jq '.[0].databaseId // empty')
  [[ -n "$run_id" ]] && break
  sleep 5
done
[[ -n "$run_id" ]] || { warn "No release run appeared. Check https://github.com/$REPO/actions"; exit 1; }
if gh run watch "$run_id" --repo "$REPO" --exit-status; then
  say "Release published:"
  open_url "https://github.com/$REPO/releases/tag/$TAG"
else
  warn "The release workflow failed. Open it to read the first red step:"
  open_url "https://github.com/$REPO/actions/runs/$run_id"
  exit 1
fi
pause

# ── Stage 6 ───────────────────────────────────────────────────────────────
stage "Install the signed APK on your phone"
say "This is the one time an uninstall is needed, because the old APK was debug-signed."
step "In the installed app, sign in and wait for 'Synced', or use Backup → Export backup."
step "Uninstall the old Lough'd In from the phone."
step "On the phone, open https://github.com/$REPO/releases/tag/$TAG and download loughdin-$version.apk."
step "Compare its SHA-256 with SHA256SUMS.txt on the same page, then install it."
step "Sign in again (or import the backup) and check the icon shows the whole keyhole."
note "Future signed APKs install straight over this one and keep local data."
pause "Press Enter when the app is installed"

finish
